### ISSUE TITLE
AttributeError: 'OpenSimplex' object has no attribute 'noise2d'

### ISSUE THREAD

**Issue by jimmykl** [serycjon/vpype-flow-imager#12]
I'm trying to run vpype-flow-imager in google colab but am getting this error

```
Traceback (most recent call last):
  File "/usr/local/bin/vpype", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/vpype_cli/cli.py", line 74, in main
    return super().main(args=preprocess_argument_list(args), **extra)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1691, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1628, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/vpype_cli/cli.py", line 128, in process_pipeline
    execute_processors(processors)
  File "/usr/local/lib/python3.7/dist-packages/vpype_cli/cli.py", line 212, in execute_processors
    state = proc(state)
  File "/usr/local/lib/python3.7/dist-packages/vpype/decorators.py", line 150, in global_processor
    state.document = f(state.document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/vpype_flow_imager/vpype_flow_imager.py", line 182, in vpype_flow_imager
    rotate=rotate,
  File "/usr/local/lib/python3.7/dist-packages/vpype_flow_imager/vpype_flow_imager.py", line 349, in draw_image
    noise_field = gen_flow_field(H, W, x_mult=mult)
  File "/usr/local/lib/python3.7/dist-packages/vpype_flow_imager/vpype_flow_imager.py", line 249, in gen_flow_field
    x_val = x_noise.noise2d(x=x_mult * x, y=x_mult * y)
AttributeError: 'OpenSimplex' object has no attribute 'noise2d'
```

I can't reproduce this locally and wonder if it's something to do with using colab + python 3.7?

**Comment by csun** [comment]
Looks like the OpenSimplex library was literally just updated and has changed this method name from `noise2d` to `noise2`.

I might poke around with fixes tomorrow but I'd guess that either pinning OpenSimplex to v0.3 or simply changing all the function names to match the new api would work.

**Comment by csun** [comment]
Just opened a PR with a potential fix for this - not sure if you can patch dependencies easily in colab but if you can please lmk if my patch fixes your problems

**Comment by jimmykl** [comment]
Thank you @csun 

I edited the file directly with your fix and it's working now 🙌
